### ISSUE TITLE
JVM Fatal Error EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by AnOddApple** [MrMan314/ninetyNinePercent#11]
Enter into blackjack game, then press exit to return to main menu and then attempt to play blackjack ASAP using the play buttons after that. The program will crash and generate this report.
Most likely an issue with Freetype.
[hs_err_pid44908.log](https://github.com/user-attachments/files/15688824/hs_err_pid44908.log)

**Comment by MrMan314** [comment]
Fixed with commit affde33276e3e4c86253a6bce32b7d0be52ab715
